// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTX8OkaA5Q-9L1Fv6n26C1PYnoqqDydJU',
    appId: '1:499920738659:web:2833e789d07867bd6c9b56',
    messagingSenderId: '499920738659',
    projectId: 'mediease-9ee78',
    authDomain: 'mediease-9ee78.firebaseapp.com',
    storageBucket: 'mediease-9ee78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxf5gB9aJpZ5GUuhG5-AundL1W0E1a9_w',
    appId: '1:499920738659:android:576c4762e33c83c06c9b56',
    messagingSenderId: '499920738659',
    projectId: 'mediease-9ee78',
    storageBucket: 'mediease-9ee78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNrkCVvXYycrzVXepiWR8GzjF9LKeK8c',
    appId: '1:499920738659:ios:0e7d55613b0cb0836c9b56',
    messagingSenderId: '499920738659',
    projectId: 'mediease-9ee78',
    storageBucket: 'mediease-9ee78.firebasestorage.app',
    iosBundleId: 'com.example.mediease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNrkCVvXYycrzVXepiWR8GzjF9LKeK8c',
    appId: '1:499920738659:ios:0e7d55613b0cb0836c9b56',
    messagingSenderId: '499920738659',
    projectId: 'mediease-9ee78',
    storageBucket: 'mediease-9ee78.firebasestorage.app',
    iosBundleId: 'com.example.mediease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTX8OkaA5Q-9L1Fv6n26C1PYnoqqDydJU',
    appId: '1:499920738659:web:6eaf2efa2990d93c6c9b56',
    messagingSenderId: '499920738659',
    projectId: 'mediease-9ee78',
    authDomain: 'mediease-9ee78.firebaseapp.com',
    storageBucket: 'mediease-9ee78.firebasestorage.app',
  );
}
